# ARG DEBIAN_FRONTEND=noninteractive
From ubuntu:noble as ffnc
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /
COPY ./deploy/sources.list /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y libopus-dev libopus0 opus-tools libssl-dev libffi-dev gcc g++ make cmake curl openssl pkg-config libwebrtc-audio-processing-dev clang
# COPY ./deploy/rustup-init ./
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN /bin/bash -c "source '$HOME/.cargo/env'"
# COPY ./deploy/config-global /root/.cargo/config

RUN mkdir /app

WORKDIR /app
COPY ./.cargo /app/.cargo
COPY ./cert /app/cert
COPY ./crates /app/crates
COPY ./libs /app/libs
COPY ./models /app/models
COPY ./src /app/src
COPY ./static /app/static
COPY ./Cargo.toml /app/Cargo.toml
COPY ./Cargo.lock /app/Cargo.lock
COPY ./log4rs.yaml /app/log4rs.yaml
COPY ./.env /app/.env

# RUN apt-get install -y libwebrtc-audio-processing-dev
# RUN apt-get install -y clang
RUN /root/.cargo/bin/cargo build --release

RUN mv /app/target/release/DigtalTalk ./
RUN rm -rf ./crates ./Cargo.toml ./Cargo.lock ./src ./target
RUN mkdir /app/logs

EXPOSE 10000 10001 31401

CMD ["./DigtalTalk"]
